install:
  # TeX Live
  - source ./scripts/texlive.sh

  # Lua 5.3, Luarocks
  - sudo apt-get install lua5.3 liblua5.3-dev
  - sudo apt-get install luarocks
  - sudo luarocks install busted
  - sudo luarocks install serpent

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_script:
  - eval $(luarocks path --bin)

script: make test
