jobs:
  include:
    - os: linux
      dist: focal

install:
  # TeX Live
  - source ./.travis/texlive.sh
  - cp ./.travis/texmf.cnf /tmp/texlive/

  # Lua 5.3, Luarocks
  - sudo apt-get install liblua5.3-0 liblua5.3-dev lua5.3
  - sudo apt-get install luarocks
  - luarocks install --local busted
  - luarocks install --local serpent

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_script:
  - eval $(luarocks path --bin)

script: make test
